name: script_tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      
jobs:
  script_tests:
    runs-on: ubuntu-latest
    name: Executes script tests in Docker
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Execute
      uses: .github/script_tests/action.yml@v1
      with:
        commitish: ${GITHUB_REF##*/}

